//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myRep_app
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedicalEnquiry
    {
        public int meID { get; set; }
        public string Question { get; set; }
        public string Answer { get; set; }
        public System.DateTime ExpectedAnswerDate { get; set; }
        public int MeetingID { get; set; }
    
        public virtual Meeting Meeting { get; set; }
    }
}
