//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myRep_app
{
    using System;
    using System.Collections.Generic;
    
    public partial class Meeting
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Meeting()
        {
            this.MedicalEnquiry = new HashSet<MedicalEnquiry>();
        }
    
        public int meetingID { get; set; }
        public int HCPID { get; set; }
        public int UserID { get; set; }
        public System.DateTime Date { get; set; }
        public string Type { get; set; }
        public string Topic { get; set; }
        public int ProductID { get; set; }
        public string NextMtgNote { get; set; }
        public Nullable<int> MedicalEnquiryID { get; set; }
        public Nullable<int> SampleDrop { get; set; }
        public Nullable<int> SampleDropQty { get; set; }
        public int UserID1 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MedicalEnquiry> MedicalEnquiry { get; set; }
        public virtual Product Product { get; set; }
        public virtual User UserSet { get; set; }
        public virtual HCP HCPSet1 { get; set; }
    }
}
