//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myRep_app
{
    using System;
    using System.Collections.Generic;
    
    public partial class SampleWarehouse
    {
        public int Id { get; set; }
        public int UserID { get; set; }
        public int SampleID { get; set; }
        public int Qty { get; set; }
    
        public virtual User User { get; set; }
        public virtual Sample Sample { get; set; }
    }
}
