//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myRep_app
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserCredentialsSet
    {
        public int UCID { get; set; }
        public int UserID { get; set; }
        public string PWD { get; set; }
    
        public virtual User UserSet { get; set; }
    }
}
